### ISSUE TITLE
Components / Content / Tabs

### ISSUE THREAD

**Issue by allozaur** [naked-ui/vue#29]

**Comment by ibockowsky** [comment]
@allozaur 
There's an animation that I need help with:
![hfCGe2dw5P](https://user-images.githubusercontent.com/22965136/116392821-31edfe80-a821-11eb-8442-ebb0799188bd.gif)
Could you check it, please?

**Comment by allozaur** [comment]
@ibockowsky

I have refactored the code and also removed unnecessary `items` option that allowed us to display tabs via data without slots. I think that slots give us everything we need so i opt for this option only. Additionally i have cleaned up the styling
